# Generated by Django 4.2.3 on 2023-07-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kudandaza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix_de_vente',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='quantite',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_de_vente_unitaire',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='quantite_vendu',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vente',
            name='prix_de_vente_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Kudandaza.produit'),
        ),
    ]
