# Generated by Django 4.2.3 on 2023-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudandaza', '0002_remove_produit_prix_de_vente_remove_vente_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_de_vente_unitaire',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vente',
            name='prix_de_vente_total',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
