# Generated by Django 4.2.3 on 2023-07-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudandaza', '0004_vente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='prix_de_vente_total',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vente',
            name='quantite_vendu',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
