# Generated by Django 4.2.3 on 2023-07-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudandaza', '0005_alter_vente_prix_de_vente_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='quantite_vendu',
            field=models.IntegerField(max_length=100),
        ),
    ]
