# Generated by Django 4.2.3 on 2023-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kudandaza', '0006_alter_vente_quantite_vendu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_de_vente_unitaire',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vente',
            name='quantite_vendu',
            field=models.IntegerField(),
        ),
    ]
