# Generated by Django 4.2.3 on 2023-08-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kudandaza', '0007_alter_produit_prix_de_vente_unitaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='user',
        ),
    ]
